---
# - name: Copy k8s Google Public signing key Ubuntu
#   copy:
#     src: kubernetes-apt-keyring.gpg
#     dest: /etc/apt/keyrings/
#     force: true
#   when: ansible_facts['distribution'] == "Ubuntu"

- name: Download k8s Google Public signing key Ubuntu
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kube_major_minor }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    force: true
  when: ansible_facts.distribution_version > '20.04'

- name: Add Kubernetes Google Public signing key to keyring Focal
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kube_major_minor }}/deb/Release.key"
    force: true
    dest: /tmp/kubernetes-apt-keyring
  when: ansible_facts.distribution_version == '20.04'

- name: Convert GPG key from ASCII to binary format
  command: gpg --dearmor -o /tmp/kubernetes-apt-keyring.gpg /tmp/kubernetes-apt-keyring
  register: dearmor_output
  when: ansible_facts.distribution_version == '20.04'

- name: Save the converted GPG key to keyring
  copy:
    src: /tmp/kubernetes-apt-keyring.gpg
    remote_src: true
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    owner: root
    group: root
    mode: '0644'
  when: dearmor_output.rc == 0 and ansible_facts.distribution_version == '20.04'

- name: Update APT package list
  apt:
    update_cache: yes
  when: ansible_facts.distribution_version == '20.04'

- name: Add k8s repo Ubuntu
  copy:
    src: deb_repo
    dest: /etc/apt/sources.list.d/kubernetes.list
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Add k8s repo CentOS
  copy:
    src: redhat_repo
    dest: /etc/yum.repos.d/kubernetes.repo
  when: ansible_facts['distribution'] == "CentOS"
