---
- name: Copy k8s Google Public signing key Debian
  copy:
    src: kubernetes-archive-keyring.gpg
    dest: /usr/share/keyrings/
  when: ansible_facts['distribution'] == "Debian"

- name: Add k8s repo Debian
  copy:
    src: deb_repo
    dest: /etc/apt/sources.list.d/
  when: ansible_facts['distribution'] == "Debian"

- name: Add k8s repo RedHat
  copy:
    src: redhat_repo
    dest: /etc/yum.repos.d/
  when: ansible_facts['distribution'] == "CentOS"