---
- name: 'Install kubectl Ubuntu'
  apt:
    name: kubectl='{{ kubectl_version }}'
    state: present
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: 'Install kubectl CentOS'
  yum:
    name: kubectl='{{ kubectl_version }}'
    state: present
  when: ansible_facts['distribution'] == "CentOS"

- name: 'Install kubelet Ubuntu'
  apt:
    name: kubelet='{{ kubelet_version }}'
    state: present
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: 'Install kubelet CentOS'
  yum:
    name: kubelet='{{ kubelet_version }}'
    state: present
  when: ansible_facts['distribution'] == "CentOS"

- name: 'Install kubeadm Ubuntu'
  apt:
    name: kubeadm='{{ kubeadm_version }}'
    state: present
    update_cache: yes

  when: ansible_facts['distribution'] == "Ubuntu"

- name: 'Install kubeadm CentOS'
  yum:
    name: kubeadm='{{ kubeadm_version }}'
    state: present
  when: ansible_facts['distribution'] == "CentOS"

- name: Prevent upgrading k8s packages (Ubuntu)
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  when: ansible_facts['distribution'] == "Ubuntu"
  loop:
  - kubeadm
  - kubectl
  - kubelet
