---
- name: Delete cluster_name A record from BIND DNS
  community.general.nsupdate:
    server: "{{ dns_server }}"
    zone: "{{ cluster_name.split('.')[1:] | join('.') }}"
    record: "{{ cluster_name.split('.')[0] }}"
    value: "{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}"
    type: A
    state: absent
    key_name: "{{ dns_tsig_key_name | default(omit) }}"
    key_secret: "{{ dns_tsig_key_secret | default(omit) }}"
    key_algorithm: "{{ dns_tsig_key_algorithm | default(omit) }}"
  when:
    - "'masters' in group_names"
    - "'destroy' in ansible_run_tags"
  tags:
    - destroy
  delegate_to: localhost