---
- name: Check if cluster_name resolves
  shell:
    cmd: nslookup "{{ cluster_name }}"

- name: kubeadm init controlpane
  shell:
    cmd: kubeadm init --apiserver-advertise-address {{ ansible_default_ipv4['address']|quote }} --apiserver-cert-extra-sans {{ cluster_name|quote }} --control-plane-endpoint {{ cluster_name|quote }} --pod-network-cidr {{ pod_cidr|quote }}
  when: "'masters' in group_names"