---
- name: Check if cluster_name resolves
  shell:
    cmd: nslookup "{{ cluster_name }}"

- name: Copy kubeadm config file
  template:
    src: kubeadm-config.j2
    dest: /tmp/kubeadm-config.yaml
  when: "'masters' in group_names"

- name: kubeadm init controlpane
  shell:
    cmd: kubeadm init --config /tmp/kubeadm-config.yaml
  when: "'masters' in group_names"
  ignore_errors: true
