---
- name: Check if cluster_name resolves
  shell:
    cmd: nslookup "{{ cluster_name }}"

- name: Copy kubeadm config file
  template:
    src: kubeadm-config-v1beta4.j2
    dest: /tmp/kubeadm-config.yaml
  when: "'masters' in group_names"

- name: kubeadm init controlpane
  shell:
    cmd: kubeadm init --config /tmp/kubeadm-config.yaml --ignore-preflight-errors=Port-10250
  when: "'masters' in group_names"
  ignore_errors: true

- name: Wait for Kubernetes API to become healthy
  uri:
    url: "https://{{ cluster_name }}:6443/healthz"
    method: GET
    validate_certs: no  # Set to 'yes' if you have proper CA certs
    status_code: 200
  register: result
  retries: 36
  delay: 5
  until: result.status == 200

- name: Set trust-domain annotation in configmap
  command: "kubectl annotate configmap kubeadm-config -n kube-system omega.k8s.io/spire-trustdomain={{ trust_domain }}"
  when: "'masters' in group_names"
  ignore_errors: true
  register: result
  retries: 50
  delay: 10
  until: result.rc == 0
