---
- name: 'Install containerd binaries'
  unarchive:
    src: containerd-{{ containerd_version }}-linux-amd64.tar.gz
    dest: /usr/local

- name: 'Copy containerd.service'
  copy:
    src: containerd.service
    dest: /usr/local/lib/systemd/system/
    owner: root
    group: root

- name: 'Installing runc'
  copy:
    src: runc.amd64
    dest: /usr/local/sbin/runc
    mode: 0755


- name: 'Systemctl daemon reload and start containerd'
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes

- name: create dir /opt/cni
  file:
    path: /opt/cni/bin
    state: directory

- name: 'Installing CNI plugins'
  unarchive:
    src: cni-plugins-linux-amd64-v{{ cni_plugins_version }}.tgz
    dest: /opt/cni/bin

- name: create containerd config path
  file:
    path: /etc/containerd
    state: directory

- name: create containerd.toml
  shell:
    cmd: containerd config default | sudo tee /etc/containerd/config.toml

- name: restart containerd
  service:
    name: containerd
    state: restarted
    enabled: yes
