---
- name: Calculate first_ip
  set_fact:
    first_ip: "{{ metallb_cidr|ansible.utils.ipaddr('2') | split('/') | first }}"

- name: Calculate last_ip
  set_fact:
    last_ip: "{{ metallb_cidr | ansible.utils.ipaddr('-5') | split('/') | first }}"

- name: Calculate adress_pool
  set_fact:
    metallb_address_pool: "{{ first_ip }}-{{ last_ip }}"

- name: Deploy metallb load balancer
  command: "kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml"
  ignore_errors: true
  register: result
  retries: 5
  delay: 10
  until: result.rc == 0

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: /root/metallb  # Change to your desired directory
    state: directory
    mode: '0755'

- name: Deploy metallb ip address pool config template
  template:
    src: ipaddresspool.j2
    dest: /root/metallb/metallb_ipaddresspool.yaml

- name: Deploy metallb ipaddresspool config
  command: "kubectl apply -f /root/metallb/metallb_ipaddresspool.yaml"
  register: result
  retries: 5
  delay: 10
  until: result.rc == 0
  ignore_errors: true