---
- name: Get kubectl version
  shell:
    cmd: kubectl version | base64 | tr -d '\n'
  register: kctl_ver

- name: Install Weave network
  kubernetes.core.k8s:
    state: present
    src: https://cloud.weave.works/k8s/net?k8s-version="{{ kctl_ver }}"