---
- name: Compute lb address range from CIDR
  set_fact:
    network: "{{ cidr | ansible.utils.ipaddr('network') }}"
    broadcast: "{{ cidr | ansible.utils.ipaddr('broadcast') }}"
    first_ip: "{{ network | ansible.utils.ipaddr('next_usable') }}"
    last_ip: "{{ broadcast | ansible.utils.ipaddr('previous_usable') }}"
    metallb_address_pool_x: "{{ (metallb_cidr | ansible.netcommon.ipaddr('hostnetwork'))[1] }}-{{ (metallb_cidr | ansible.netcommon.ipaddr('hostnetwork'))[-2] }}"
    metallb_address_pool: "{{ first_ip }}-{{ last_ip }}"

- name: Deploy metallb load balancer
  command: "kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml"
  ignore_errors: true

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: /root/metallb  # Change to your desired directory
    state: directory
    mode: '0755'

- name: Deploy metallb ip address pool config template
  template:
    src: ipaddresspool.j2
    dest: /root/metallb/metallb_ipaddresspool.yaml

- name: Deploy metallb ipaddresspool config
  command: "kubectl apply -f /root/metallb/metallb_ipaddresspool.yaml"
  ignore_errors: true