---
- name: Calculate first_ip
  set_fact:
    first_ip: "{{ metallb_cidr | ansible.utils.ipaddr('2') | split('/') | first }}"
    master_ip: "{{ ansible_default_ipv4.address }}"


- name: Calculate last_ip
  set_fact:
    last_ip: "{{ metallb_cidr | ansible.utils.ipaddr('-5') | split('/') | first }}"

- name: Calculate adress_pool
  set_fact:
    metallb_address_pool: "{{ first_ip }}-{{ last_ip }}"

- name: Deploy metallb load balancer
  command: "kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml"
  ignore_errors: true
  register: result
  retries: 5
  delay: 10
  until: result.rc == 0

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: /root/metallb  # Change to your desired directory
    state: directory
    mode: '0755'

- name: Deploy metallb ip address pool config template
  template:
    src: ipaddresspool.j2
    dest: /root/metallb/metallb_ipaddresspool.yaml

- name: Deploy metallb ipaddresspool config
  command: "kubectl apply -f /root/metallb/metallb_ipaddresspool.yaml"
  register: result
  retries: 5
  delay: 10
  until: result.rc == 0
  ignore_errors: true

- name: Add static route to {{ net1 }} via {{ ip2 }} in route-en3s2
  lineinfile:
    path: /etc/sysconfig/network-scripts/route-enp2s0
    line: "{{ metallb_cidr }} via {{ master_ip }} dev enp2s0"
    state: present
    create: yes
    mode: '0644'
  become: yes
  delegate_to: omegart01

- name: Add static route comment to {{ net1 }} via {{ ip2 }} in route-en3s2
  lineinfile:
    path: /etc/sysconfig/network-scripts/route-enp2s0
    line: "# {{ metallb_cidr }} via {{ master_ip }} dev enp2s0  {{ cluster_name }}"
    state: present
    create: yes
    mode: '0644'
  become: yes
  delegate_to: omegart01

- name: Restart network service on router1
  ansible.builtin.systemd:
    name: network
    state: restarted
    enabled: yes
  become: yes
  delegate_to: omegart01