---
- name: Get kubectl version
  shell:
    cmd: echo $(kubectl version | base64 | tr -d '\n')
  register: kctl_ver

- name: debug out
  debug:
    msg: "{{ kctl_ver.stdout }}"

- name: Download weave definition file
  shell:
    cmd: curl -L https://cloud.weave.works/k8s/net?k8s-version="{{ kctl_ver.stdout|quote }}" --output /tmp/weave.yaml

- name: Install Weave network
  kubernetes.core.k8s:
    state: present
    src: /tmp/weave.yaml