---
- name: Deploy admin-kubeconfig.sh
  copy:
    dest: /usr/local/bin/admin-kubeconfig.sh
    src: admin-kubeconfig.sh
    mode: '0755'
    owner: root
    group: root
  when: "'masters' in group_names"

- name: Create crontab for admin-kubeconfig
  ansible.builtin.cron:
    name: "Update admin kubeconfig secret"
    job: "/usr/local/bin/admin-kubeconfig.sh >> /var/log/kubeconfig-secret.log 2>&1"
    special_time: "hourly"
  when: "'masters' in group_names"
