---
- name: Installing containerd
  import_tasks: install_containerd.yaml

- name: Installing pre-req packages
  import_tasks: install_k8s_prereqs.yaml

- name: Add k8s apt repo
  import_tasks: add_k8s_repo.yaml

- name: Install main k8s packages
  import_tasks: base_k8s_install.yaml

- name: Install controlplane
  import_tasks: deploy_controlplane.yaml
  when: "'masters' in group_names"

- name: Create kubeconfig
  import_tasks: create_kube_config.yaml
  when: "'masters' in group_names"

- name: Install WeaveWorks network
  import_tasks: install_k8s_network.yaml
  when: "'masters' in group_names"

- name: Register join command
  import_tasks: register_joincmd.yaml
  when: '"masters" in group_names'

- name: Register worker nodes
  import_tasks: register_workers.yaml
  when: "'workers' in group_names"

- name: Install nfs_common
  import_tasks: install_nfs_common.yaml

- name: Deploy helm binary
  import_tasks: install_helm.yaml
  when: '"masters" in group_names'

- name: Deploy nfs storage_class
  import_tasks: install_nfs_sc.yaml
  when: '"masters" in group_names'

- name: Deploy stern binary
  import_tasks: install_stern.yaml
  when: '"masters" in group_names'

- name: Deploy metal-lb load balancer
  import_tasks: install_metallb.yaml
  when: '"masters" in group_names'
