---
- name: Register join command
  shell:
    cmd: kubeadm token create --print-join-command
    register: join_cmd
  when: "'masters' in group_names"

- name: Register Worker node
  shell:
    cmd: "{{ join_cmd.stdout }}"
  when: "'workers' in group_names"